on:
  push:
    branches:
      - main
jobs:
  build:
    name: 'Build and test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'
      - name: Add test hosts to /etc/hosts
        run: |
          echo "127.0.0.1 multiflare.test www.multiflare.test api.multiflare.test account.multiflare.test" | sudo tee -a /etc/hosts
      - name: Open port 80
        # https://stackoverflow.com/a/23281417/612202
        run: |
          sudo setcap cap_net_bind_service=+ep `readlink -f \`which node\``
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - run: yarn build
      - name: Run multiflare
        run: |
          yarn multiflare ./example/multiflare/workers &
          export MULTIFLARE_PID=$!
          sleep 2
          yarn test
          kill $MULTIFLARE_PID
