on:
  push:
    branches:
      - main
jobs:
  build:
    name: 'Build and test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'
      - name: Add test hosts to /etc/hosts
        run: |
          echo "127.0.0.1 my-workshop.test www.my-workshop.test api.my-workshop.test account.my-workshop.test" | sudo tee -a /etc/hosts
      - name: Open port 80
        # https://stackoverflow.com/a/23281417/612202
        run: |
          sudo apt install libcap2-bin
          sudo setcap cap_net_bind_service=+ep `readlink -f \`which node\``

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - run: yarn build
      - name: Run multiflare
        run: |
          node --experimental-vm-modules src/cli.js ./example/my-workshop/workers &
          export MULTIFLARE_PID=$!
          sleep 2
          node --experimental-vm-modules node_modules/jest/bin/jest.js
          kill $MULTIFLARE_PID
