on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: 'Build and test'
    runs-on: ubuntu-latest
    steps:
      - name: Install yarn if needed
        if: ${{ env.ACT }}
        run: npm install -g yarn
      - uses: actions/checkout@v2
      # if in ACT local runner
      - uses: actions/setup-node@v2
        if: ${{ env.ACT }}
        with:
          node-version: '16.x'
      # else github action
      - uses: actions/setup-node@v2
        if: ${{ !env.ACT }}
        with:
          node-version: '16.x'
          cache: 'yarn'
      - name: Add test hosts to /etc/hosts
        run: |
          echo "127.0.0.1 multiflare.test www.multiflare.test api.multiflare.test blog.multiflare.test chat.multiflare.test" | sudo tee -a /etc/hosts
      - name: Open port 80
        # https://stackoverflow.com/a/23281417/612202
        run: sudo setcap cap_net_bind_service=+ep `readlink -f \`which node\``
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Run test
        run: yarn test
