on:
  workflow_dispatch:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Add test hosts to /etc/hosts
        run: |
          echo "127.0.0.1 multiflare.test www.multiflare.test api.multiflare.test blog.multiflare.test chat.multiflare.test" | sudo tee -a /etc/hosts
      - name: Open port 80
        # https://stackoverflow.com/a/23281417/612202
        run: sudo setcap cap_net_bind_service=+ep `readlink -f \`which node\``
      - run: yarn install --frozen-lockfile
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}
